################################################## 
# Notification_services_types.py 
# generated by ZSI.generate.wsdl2python
##################################################


import ZSI
import ZSI.TCcompound
from ZSI.schema import LocalElementDeclaration, ElementDeclaration, TypeDefinition, GTD, GED
from ZSI.generate.pyclass import pyclass_type

##############################
# targetNamespace
# http://broker.remote.expres.psnc.pl/xsd
##############################

class ns0:
    targetNamespace = "http://broker.remote.expres.psnc.pl/xsd"

    class ChunkInfo_Def(ZSI.TCcompound.ComplexType, TypeDefinition):
        schema = "http://broker.remote.expres.psnc.pl/xsd"
        type = (schema, "ChunkInfo")
        def __init__(self, pname, ofwhat=(), attributes=None, extend=False, restrict=False, **kw):
            ns = ns0.ChunkInfo_Def.schema
            TClist = [ZSI.TCnumbers.Iint(pname=(ns,"chunkId"), aname="_chunkId", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"chunkLocation"), aname="_chunkLocation", minOccurs=1, maxOccurs=1, nillable=True, typed=False, encoded=kw.get("encoded")), ZSI.TC.String(pname=(ns,"translationNodeIP"), aname="_translationNodeIP", minOccurs=1, maxOccurs=1, nillable=True, typed=False, encoded=kw.get("encoded")), ZSI.TCnumbers.Iint(pname=(ns,"translationNodeId"), aname="_translationNodeId", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            self.attribute_typecode_dict = attributes or {}
            if extend: TClist += ofwhat
            if restrict: TClist = ofwhat
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, pname=pname, inorder=0, **kw)
            class Holder:
                __metaclass__ = pyclass_type
                typecode = self
                def __init__(self):
                    # pyclass
                    self._chunkId = None
                    self._chunkLocation = None
                    self._translationNodeIP = None
                    self._translationNodeId = None
                    return
            Holder.__name__ = "ChunkInfo_Holder"
            self.pyclass = Holder

    class chunkIsReady_Dec(ZSI.TCcompound.ComplexType, ElementDeclaration):
        literal = "chunkIsReady"
        schema = "http://broker.remote.expres.psnc.pl/xsd"
        def __init__(self, **kw):
            ns = ns0.chunkIsReady_Dec.schema
            TClist = [ZSI.TCnumbers.Iint(pname=(ns,"param0"), aname="_param0", minOccurs=1, maxOccurs=1, nillable=True, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("http://broker.remote.expres.psnc.pl/xsd","chunkIsReady")
            kw["aname"] = "_chunkIsReady"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self,None,TClist,inorder=0,**kw)
            class Holder:
                __metaclass__ = pyclass_type
                typecode = self
                def __init__(self):
                    # pyclass
                    self._param0 = None
                    return
            Holder.__name__ = "chunkIsReady_Holder"
            self.pyclass = Holder

    class chunkIsReadyResponse_Dec(ZSI.TCcompound.ComplexType, ElementDeclaration):
        literal = "chunkIsReadyResponse"
        schema = "http://broker.remote.expres.psnc.pl/xsd"
        def __init__(self, **kw):
            ns = ns0.chunkIsReadyResponse_Dec.schema
            TClist = [GTD("http://broker.remote.expres.psnc.pl/xsd","ChunkInfo",lazy=False)(pname=(ns,"return"), aname="_return", minOccurs=1, maxOccurs=1, nillable=True, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("http://broker.remote.expres.psnc.pl/xsd","chunkIsReadyResponse")
            kw["aname"] = "_chunkIsReadyResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self,None,TClist,inorder=0,**kw)
            class Holder:
                __metaclass__ = pyclass_type
                typecode = self
                def __init__(self):
                    # pyclass
                    self._return = None
                    return
            Holder.__name__ = "chunkIsReadyResponse_Holder"
            self.pyclass = Holder

    class ChunkInfo_Dec(ElementDeclaration):
        literal = "ChunkInfo"
        schema = "http://broker.remote.expres.psnc.pl/xsd"
        def __init__(self, **kw):
            kw["pname"] = ("http://broker.remote.expres.psnc.pl/xsd","ChunkInfo")
            kw["aname"] = "_ChunkInfo"
            if ns0.ChunkInfo_Def not in ns0.ChunkInfo_Dec.__bases__:
                bases = list(ns0.ChunkInfo_Dec.__bases__)
                bases.insert(0, ns0.ChunkInfo_Def)
                ns0.ChunkInfo_Dec.__bases__ = tuple(bases)

            ns0.ChunkInfo_Def.__init__(self, **kw)
            if self.pyclass is not None: self.pyclass.__name__ = "ChunkInfo_Dec_Holder"

# end class ns0 (tns: http://broker.remote.expres.psnc.pl/xsd)
