##################################################
# Notification_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.ServiceModuleWriter
#
##################################################

from Notification_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class Notification(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<wsdl:definitions targetNamespace=\"http://broker.remote.expres.psnc.pl\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http/\" xmlns:mime=\"http://schemas.xmlsoap.org/wsdl/mime/\" xmlns:nsNf=\"http://broker.remote.expres.psnc.pl\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:soap12=\"http://schemas.xmlsoap.org/wsdl/soap12/\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:xsd=\"http://broker.remote.expres.psnc.pl/xsd\">
	<wsdl:types>
		<xs:schema attributeFormDefault=\"qualified\" elementFormDefault=\"qualified\" targetNamespace=\"http://broker.remote.expres.psnc.pl/xsd\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">
			<xs:element name=\"chunkIsReady\">
				<xs:complexType>
					<xs:sequence>
						<xs:element name=\"param0\" nillable=\"true\" type=\"xs:int\"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name=\"chunkIsReadyResponse\">
				<xs:complexType>
					<xs:sequence>
						<xs:element name=\"return\" nillable=\"true\" type=\"xsd:ChunkInfo\"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name=\"ChunkInfo\" type=\"xsd:ChunkInfo\"/>
			<xs:complexType name=\"ChunkInfo\">
				<xs:sequence>
					<xs:element name=\"chunkId\" type=\"xs:int\"/>
					<xs:element name=\"chunkLocation\" nillable=\"true\" type=\"xs:string\"/>
					<xs:element name=\"translationNodeIP\" nillable=\"true\" type=\"xs:string\"/>
					<xs:element name=\"translationNodeId\" type=\"xs:int\"/>
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name=\"chunkIsReadyMessage\">
		<wsdl:part element=\"xsd:chunkIsReady\" name=\"part1\"/>
	</wsdl:message>
	<wsdl:message name=\"chunkIsReadyResponseMessage\">
		<wsdl:part element=\"xsd:chunkIsReadyResponse\" name=\"part1\"/>
	</wsdl:message>
	<wsdl:portType name=\"NotificationPortType\">
		<wsdl:operation name=\"chunkIsReady\">
			<wsdl:input message=\"nsNf:chunkIsReadyMessage\" wsaw:Action=\"urn:chunkIsReady\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\"/>
			<wsdl:output message=\"nsNf:chunkIsReadyResponseMessage\" wsaw:Action=\"urn:chunkIsReady\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name=\"NotificationSOAP11Binding\" type=\"nsNf:NotificationPortType\">
		<soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
		<wsdl:operation name=\"chunkIsReady\">
			<soap:operation soapAction=\"urn:chunkIsReady\" style=\"document\"/>
			<wsdl:input>
				<soap:body use=\"literal\"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use=\"literal\"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:binding name=\"NotificationSOAP12Binding\" type=\"nsNf:NotificationPortType\">
		<soap12:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
		<wsdl:operation name=\"chunkIsReady\">
			<soap12:operation soapAction=\"urn:chunkIsReady\" style=\"document\"/>
			<wsdl:input>
				<soap12:body use=\"literal\"/>
			</wsdl:input>
			<wsdl:output>
				<soap12:body use=\"literal\"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name=\"Notification\">
		<wsdl:port binding=\"nsNf:NotificationSOAP11Binding\" name=\"NotificationSOAP11port\">
			<soap:address location=\"http://melisa.man.poznan.pl:8080/axis2/services/Notification\"/>
		</wsdl:port>
		<wsdl:port binding=\"nsNf:NotificationSOAP12Binding\" name=\"NotificationSOAP12port\">
			<soap12:address location=\"http://melisa.man.poznan.pl:8080/axis2/services/Notification\"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>"""

    def __init__(self, post='/axis2/services/Notification', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_chunkIsReady(self, ps):
        self.request = ps.Parse(chunkIsReadyMessage.typecode)
        return chunkIsReadyResponseMessage()

    soapAction['urn:chunkIsReady'] = 'soap_chunkIsReady'
    root[(chunkIsReadyMessage.typecode.nspname,chunkIsReadyMessage.typecode.pname)] = 'soap_chunkIsReady'

    def soap_chunkIsReady(self, ps):
        self.request = ps.Parse(chunkIsReadyMessage.typecode)
        return chunkIsReadyResponseMessage()

    soapAction[''] = 'soap_chunkIsReady'
    root[(chunkIsReadyMessage.typecode.nspname,chunkIsReadyMessage.typecode.pname)] = 'soap_chunkIsReady'

