##################################################
# TranslationNode_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.ServiceModuleWriter
#
##################################################

from TranslationNode_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class TranslationNode(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<wsdl:definitions targetNamespace=\"http://tr.remote.expres.psnc.pl\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http/\" xmlns:mime=\"http://schemas.xmlsoap.org/wsdl/mime/\" xmlns:nsTr=\"http://tr.remote.expres.psnc.pl\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:soap12=\"http://schemas.xmlsoap.org/wsdl/soap12/\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:xsd=\"http://tr.remote.expres.psnc.pl/xsd\">
	<wsdl:types>
		<xs:schema attributeFormDefault=\"qualified\" elementFormDefault=\"qualified\" targetNamespace=\"http://tr.remote.expres.psnc.pl/xsd\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">
			<xs:element name=\"startTranslationJob\">
				<xs:complexType>
					<xs:sequence>
						<xs:element name=\"param0\" nillable=\"true\" type=\"xsd:JobInfo\"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name=\"JobInfo\" type=\"xsd:JobInfo\"/>
			<xs:complexType name=\"JobInfo\">
				<xs:sequence>
					<xs:element name=\"brokerIPAddress\" nillable=\"true\" type=\"xs:string\"/>
					<xs:element name=\"chunkSize\" type=\"xs:long\"/>
					<xs:element name=\"endTime\" nillable=\"true\" type=\"xs:string\"/>
					<xs:element name=\"startTime\" nillable=\"true\" type=\"xs:string\"/>
					<xs:element name=\"stationName\" nillable=\"true\" type=\"xs:string\"/>
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name=\"startTranslationJobMessage\">
		<wsdl:part element=\"xsd:startTranslationJob\" name=\"part1\"/>
	</wsdl:message>
	<wsdl:portType name=\"TranslationNodePortType\">
		<wsdl:operation name=\"startTranslationJob\">
			<wsdl:input message=\"nsTr:startTranslationJobMessage\" wsaw:Action=\"urn:startTranslationJob\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name=\"TranslationNodeSOAP11Binding\" type=\"nsTr:TranslationNodePortType\">
		<soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
		<wsdl:operation name=\"startTranslationJob\">
			<soap:operation soapAction=\"urn:startTranslationJob\" style=\"document\"/>
			<wsdl:input>
				<soap:body use=\"literal\"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:binding name=\"TranslationNodeSOAP12Binding\" type=\"nsTr:TranslationNodePortType\">
		<soap12:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
		<wsdl:operation name=\"startTranslationJob\">
			<soap12:operation soapAction=\"urn:startTranslationJob\" style=\"document\"/>
			<wsdl:input>
				<soap12:body use=\"literal\"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name=\"TranslationNode\">
		<wsdl:port binding=\"nsTr:TranslationNodeSOAP11Binding\" name=\"TranslationNodeSOAP11port\">
			<soap:address location=\"http://localhost:8080/axis2/services/TranslationNode\"/>
		</wsdl:port>
		<wsdl:port binding=\"nsTr:TranslationNodeSOAP12Binding\" name=\"TranslationNodeSOAP12port\">
			<soap12:address location=\"http://localhost:8080/axis2/services/TranslationNode\"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>"""

    def __init__(self, post='/axis2/services/TranslationNode', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_startTranslationJob(self, ps):
        self.request = ps.Parse(startTranslationJobMessage.typecode)
        # NO output
        return None

    soapAction['urn:startTranslationJob'] = 'soap_startTranslationJob'
    root[(startTranslationJobMessage.typecode.nspname,startTranslationJobMessage.typecode.pname)] = 'soap_startTranslationJob'

    def soap_startTranslationJob(self, ps):
        self.request = ps.Parse(startTranslationJobMessage.typecode)
        # NO output
        return None

    soapAction[''] = 'soap_startTranslationJob'
    root[(startTranslationJobMessage.typecode.nspname,startTranslationJobMessage.typecode.pname)] = 'soap_startTranslationJob'

