all:
	make -C common install prefix=${prefix}
	make -C testunit install prefix=${prefix}
	make -C netlib install prefix=${prefix}
	make -C containers install prefix=${prefix}

install:
	make -C common install prefix=${prefix}
	make -C testunit install prefix=${prefix}
	make -C netlib install prefix=${prefix}
	make -C containers install prefix=${prefix}

clean:
	make -C common clean
	make -C testunit clean
	make -C netlib clean 
	make -C containers clean
