################################################## 
# UserAccessPointService_messages.py 
# generated by ZSI.generate.wsdl2python
##################################################


from UserAccessPointService_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

getDomainClientPorts = useraccesspoint_jra3_geant2_net.getDomainClientPorts().pyclass

getDomainClientPortsResponse = useraccesspoint_jra3_geant2_net.getDomainClientPortsResponse().pyclass

modifyReservation = useraccesspoint_jra3_geant2_net.modifyReservation().pyclass

modifyReservationResponse = useraccesspoint_jra3_geant2_net.modifyReservationResponse().pyclass

getAllClientPorts = useraccesspoint_jra3_geant2_net.getAllClientPorts().pyclass

getAllClientPortsResponse = useraccesspoint_jra3_geant2_net.getAllClientPortsResponse().pyclass

cancelService = useraccesspoint_jra3_geant2_net.cancelService().pyclass

cancelServiceResponse = useraccesspoint_jra3_geant2_net.cancelServiceResponse().pyclass

queryService = useraccesspoint_jra3_geant2_net.queryService().pyclass

queryServiceResponse = useraccesspoint_jra3_geant2_net.queryServiceResponse().pyclass

submitService = useraccesspoint_jra3_geant2_net.submitService().pyclass

submitServiceResponse = useraccesspoint_jra3_geant2_net.submitServiceResponse().pyclass
